title: DevWithLC
email: vanchuyenluu@gmail.com
description: Whole development Blog.
baseurl: "/"
url: "https://chuyenlv.github.io"

github_username: chuyenlv

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
  - node_modules
