title: BlogLC
email: vanchuyenluu@gmail.com
description: Blog lập trình Website.
baseurl: ""
url: "https://chuyenluu.ga"

lang: vi

defaults:
  - scope:
      path: ""
    values:
      image: /assets/default-lc.jpg
      height: 768
      width: 1366

github_username: chuyenlv

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
  - node_modules
